spring.application.name=Authentication Service
server.port=7086

 #DataBase Connection
spring.data.mongodb.database=auth_db
 
 #Eureka Configuration
 eureka.client.register-with-eureka=true
 eureka.client.serviceUrl.defaultZone=http://localhost:7111/eureka/
 eureka.instance.hostname=localhost
 eureka.instance.virtual-host-name=AUTH-SVC
 
 #Logging Config
logging.level.root=INFO
logging.level.com.taskmanager=DEBUG
logging.level.org.springframework.web=WARN

#Swagger Config
com.taskmanager.swagger.autoconfig = true

#JWT Secret Key
